# Generated by Django 5.0.6 on 2024-05-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "countries",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("city_id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("population", models.IntegerField()),
                ("is_capital", models.BooleanField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.country",
                    ),
                ),
            ],
            options={
                "db_table": "cities",
            },
        ),
    ]
