#ifndef INCLUDED_Constants_H
#define INCLUDED_Constants_H

const int STRING_SIZE = 100;

const int DIRECTOR_ACTIVE_STATE = 1;

const int MOVIE_ACTIVE_STATE = 1;
const int MOVIE_REMOVED_STATE = 0;

const int END_MARK = -1;
const int ABSENT_MARK = -1;

const int CAN_NOT_LOAD_INDEX_FILE_ERROR_CODE = 1;
const int CAN_NOT_LOAD_FREE_SPACES_FILE_ERROR_CODE = 2;
const int CAN_NOT_LOAD_DIRECTORS_FILE_ERROR_CODE = 3;
const int CAN_NOT_LOAD_MOVIES_FILE_ERROR_CODE = 4;
const int CAN_NOT_FIND_DIRECTOR_ERROR_CODE = 5;
const int CAN_NOT_FIND_MOVIE_ERROR_CODE = 6;

#endif // !INCLUDED_Constants_H